### ISSUE TITLE
dependency upon urllib2 should be removed

### ISSUE THREAD

**Issue by azbarcea** [daradib/pypuppet#3]
It seems that python `>3.5.1`.

Also, it seems to have dependency upon `urllib2`, which is known to be poisoned ( more on [stackoverflow: need to `install-urllib2` for python 3.5.1](https://stackoverflow.com/questions/34475051/need-to-install-urllib2-for-python-3-5-1) )
```
>>> import puppet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alex\projects\daradib\pypuppet\puppet\__init__.py", line 1, in <module>
    from .api import APIError
  File "C:\Users\alex\projects\daradib\pypuppet\puppet\puppet\api.py", line 1, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```

The `urllib.request` library is already included with Python 3, instead.

**Comment by daradib** [comment]
Resolved by @norus in #1 - replaced with requests.
